import { profiles } from './profiles.js';
import { mountProfilePanel,renderProfileBadge } from './profile-panel.js';
import { localData } from './local-data.js';
import { mountCloudPanel,startCloud,disconnect } from './cloud-sync.js';
import { openGarden,gardenSummary } from './garden.js';
import { objectives } from './content.js';
import { progress } from './engine.js';
import { openQuiz } from './quiz.js';
import { openWords,mountWordReport } from './word-lab.js';
import { mountReports } from './reports.js';
import { mountExplanationPanel } from './explanations.js';
import { escapeHTML as h } from './attempts.js';
const PIN='curious-pin',root=document.querySelector('#app');
let activity=null,parentOpen=false;
function home(){activity?.dispose?.();activity=null;renderProfileBadge(root);root.className='shell';const p=localData.read().profile;
  root.innerHTML=`<section class="hero"><div class="eyebrow">Your next small step is ready</div><h1>Wonder. Try. Grow.</h1><p>Explore an idea, discover a word, and take the time you need.</p><button class="primary" data-start>Begin today’s path</button><button data-garden class="garden-link"><span class="eyebrow">An investigation</span><b>Same garden. Different fence?</b><span>Build, predict and discover area & perimeter.</span></button><div class="workshop-links"><button data-spelling><b>Listen & spell</b><span>Meet words, hear them, and remember them.</span></button><button data-meaning><b>Explore word meanings</b><span>Make sense of words in a sentence.</span></button></div><div class="features"><div class="feature"><b>At your pace</b>No countdowns or pressure.</div><div class="feature"><b>Helpful explanations</b>Try an idea another way.</div><div class="feature"><b>Your own path</b>Practice returns when it is useful.</div></div><p class="small">${h(p.displayName)} · Progress saves on this device.</p></section>`;
  root.querySelector('[data-start]').onclick=()=>{activity=openQuiz(root,home);};
  root.querySelector('[data-garden]').onclick=()=>{activity=openGarden(root,home);};
  root.querySelector('[data-spelling]').onclick=()=>{activity=openWords(root,home,'spelling');};
  root.querySelector('[data-meaning]').onclick=()=>{activity=openWords(root,home,'meaning');};
}
function parent(){if(parentOpen)return;parentOpen=true;activity?.pause?.();const b=document.createElement('div'),set=!!localStorage.getItem(PIN);b.className='backdrop';b.setAttribute('role','dialog');b.setAttribute('aria-modal','true');b.setAttribute('aria-label','Grown-up view');
  const close=()=>{b.remove();parentOpen=false;activity?.resume?.();document.querySelector('#parent').focus();};
  b.innerHTML=`<section class="modal"><button class="close">Close</button><div class="eyebrow">For grown-ups</div><h2>${set?'Enter your PIN':'Create a parent PIN'}</h2><p>${set?'Progress details are protected.':'Choose at least four digits, stored on this device.'}</p><form class="pin"><input aria-label="Parent PIN" type="password" inputmode="numeric" pattern="[0-9]{4,}" minlength="4" required><button class="primary">Continue</button></form><p data-error role="status"></p></section>`;document.body.append(b);b.querySelector('.close').onclick=close;b.querySelector('input').focus();
  let failures=0,lockedUntil=0;
  b.querySelector('form').onsubmit=e=>{e.preventDefault();if(Date.now()<lockedUntil){b.querySelector('[data-error]').textContent='Please wait a moment before trying again.';return;}const v=e.target[0].value;if(!set)localStorage.setItem(PIN,v);if(!set||localStorage.getItem(PIN)===v)dashboard(b,close);else{failures++;if(failures>=5)lockedUntil=Date.now()+30000;b.querySelector('[data-error]').textContent='That PIN did not match.';}};
}
function dashboard(b,close){const p=localData.read().profile;const secure=Object.values(p.mastery).filter(m=>['secure','settled'].includes(m.state)).length;
  b.querySelector('.modal').innerHTML=`<button class="close">Close</button><div class="eyebrow">${profiles.info().kind==='test'?'Test profile — excluded from learner reports':'Grown-up view'}</div><h2>${h(p.displayName)}’s learning</h2><p>${secure} topics currently secure or settled. These are practice estimates, not an assessment of school attainment.</p>${['maths','english'].map(s=>`<p>${s==='maths'?'Maths':'English'} curriculum practice: ${progress(p,s)}%</p>`).join('')}<section id="reports-panel"></section><details><summary>Spelling & vocabulary lists and settings</summary><section id="word-panel"></section></details><details><summary>Explanation helper</summary><section id="explain-panel"></section></details><details><summary>Concept investigation evidence</summary>${gardenSummary()}</details><details><summary>Curriculum topics</summary>${objectives.map(o=>`<p><b>${h(o.title)}</b> — ${h(p.mastery[o.id]?.state||'not explored yet')} · ${o.items.length} questions</p>`).join('')}</details><details><summary>Learning profiles</summary><section id="profiles-panel"></section></details><details><summary>Save across devices</summary><section id="cloud-panel"></section></details><p class="small">The PIN is a shared-device privacy gate, not internet-grade authentication.</p>`;
  b.querySelector('.close').onclick=close;
  const gardenEvents=(localData.read().garden?.attempts||[]).map(a=>({id:a.id,ts:a.ts||'',type:'garden-answer',data:{...a,itemId:`garden-${a.stage}`,topic:'Area & perimeter investigation',response:JSON.stringify(a.data),stem:a.stem||`Garden: ${a.stage}`}}));
  mountReports(b.querySelector('#reports-panel'),{...p,events:[...p.events,...gardenEvents].sort((a,b)=>a.ts.localeCompare(b.ts))});
  mountWordReport(b.querySelector('#word-panel'),p,event=>{try{p.events.push(event);localData.saveProfile(p);dashboard(b,close);}catch{b.querySelector('[data-range-status]').textContent='Could not save the practice range.';}});
  mountExplanationPanel(b.querySelector('#explain-panel'),p,result=>{activity?.markSupported?.();close();const card=document.createElement('section');card.className='card';card.innerHTML=`<h3>Let’s try another way</h3><p>${h(result.explanation)}</p><p>${h(result.check)}</p><button>Back to my question</button>`;root.prepend(card);activity?.pause?.();card.querySelector('button').onclick=()=>{card.remove();activity?.resume?.();};});
  mountCloudPanel(b.querySelector('#cloud-panel'));
  mountProfilePanel(b.querySelector('#profiles-panel'),()=>{home();dashboard(b,close);},async()=>{await disconnect();profiles.clearDevice();location.reload();});
}
document.querySelector('#parent').onclick=parent;home();
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js');
window.addEventListener('curious-data',e=>{if(e.detail.source==='cloud'&&e.detail.profileId===profiles.activeId&&!activity&&!parentOpen)home();});
void startCloud();
