const q=(id,tier,stem,choices,answer,hint)=>({id,tier,stem,choices,answer,hint});
export const objectives=[
['M-NPV','Number sense',1,'Place value',[],q('m1',1,'Value of 6 in 364?',['60','6','600','36'],'60','Check the hundreds, tens and ones columns.'),q('m2',2,'5 hundreds, 2 tens and 8 ones?',['528','258','5,208','825'],'528','Build hundreds, then tens, then ones.'),q('m3',3,'10 more than 796?',['806','797','896','706'],'806','Adding ten changes the tens column.')],
['M-CALC','Calculation',1,'Mental calculation',['M-NPV'],q('m4',1,'46 + 20?',['66','48','64','86'],'66','Add two tens and keep the ones.'),q('m5',2,'83 − 27?',['56','64','66','54'],'56','Subtract 20, then 7.'),q('m6',3,'128 books plus 47 more?',['175','165','185','171'],'175','Add 40, then 7.')],
['M-MULT','Multiplication',2,'Multiplication structure',['M-CALC'],q('m7',1,'7 × 4?',['28','24','32','21'],'28','Think of seven groups of four.'),q('m8',2,'If 6 × 8 = 48, what is 12 × 8?',['96','56','84','108'],'96','Doubling a factor doubles the product.'),q('m9',3,'9 trays hold 14 seedlings each. Total?',['126','116','132','96'],'126','Split 14 into 10 and 4.')],
['M-FRAC','Fractions',2,'Equivalent fractions',['M-MULT'],q('m10',1,'Which equals 1/2?',['3/6','2/3','1/3','4/6'],'3/6','The numerator is half the denominator.'),q('m11',2,'Complete: 3/4 = ?/12',['9','8','6','10'],'9','Multiply top and bottom by 3.'),q('m12',3,'Which is greater: 5/8 or 2/3?',['2/3','5/8','Equal','Cannot tell'],'2/3','Compare with a common denominator.')],
['M-MEAS','Measurement',3,'Perimeter and area',['M-CALC'],q('m13',1,'Perimeter of a 7 cm by 3 cm rectangle?',['20 cm','21 cm','10 cm','14 cm'],'20 cm','Add all four sides.'),q('m14',2,'Area of a 9 m by 4 m rectangle?',['36 m²','26 m²','13 m²','36 m'],'36 m²','Multiply length by width.'),q('m15',3,'A square has area 64 cm². Its perimeter?',['32 cm','16 cm','256 cm','8 cm'],'32 cm','Find the side, then count four sides.')],
['E-VOC','Vocabulary',1,'Words in context',[],q('e1',1,'“The path was narrow, so we walked in single file.” Narrow means…',['not wide','very long','slippery','hidden'],'not wide','Only one person could fit across.'),q('e2',2,'“Mira was reluctant to enter, but eventually stepped inside.” Reluctant means…',['unwilling','excited','unable','noisy'],'unwilling','“But” signals she did not want to at first.'),q('e3',3,'“The evidence was inconclusive, so the debate continued.” Inconclusive means…',['not proving a clear result','completely false','very detailed','secret'],'not proving a clear result','The debate was not settled.')],
['E-GRAM','Grammar',1,'Sentence structure',['E-VOC'],q('e4',1,'Verb in “The silver fish darted away”?',['darted','silver','fish','away'],'darted','Find the action.'),q('e5',2,'Which is correct?',["The dog's bowl was empty.","The dogs bowl was empty.","The dog's' bowl was empty.","The dogs' bowl was empty."],"The dog's bowl was empty.",'One dog owns the bowl: apostrophe + s.'),q('e6',3,'Subordinate clause in “Although it rained, we walked.”',['Although it rained','we walked','walked','it rained'],'Although it rained','It cannot stand alone here.')],
['E-INF','Reading',2,'Inference from evidence',['E-VOC'],q('e7',1,'“Amir zipped his coat and pulled his hat low.” The weather is probably…',['cold','hot','warm','unknown'],'cold','The clothing gives a clue.'),q('e8',2,'“Lena checked the clock again. Her foot tapped.” She is probably…',['anxious or impatient','sleepy','proud','confused'],'anxious or impatient','Both actions show tension.'),q('e9',3,'“Jon hid the cracked trophy behind books.” We can infer…',['he may be hiding damage','he is displaying it','he plans to read','it is new'],'he may be hiding damage','Its condition and position are evidence.')],
['E-SUM','Reading',2,'Summarising',['E-INF'],q('e10',1,'A paragraph explains how bees turn nectar into honey. Best summary?',['How bees make honey','Where flowers grow','Why honey is sweet','Bee species'],'How bees make honey','Keep the central idea.'),q('e11',2,'Someone misses a bus, cycles through rain, and reaches a concert. Best summary?',['They overcome delays to reach a concert','It rains by a bus stop','They own a bicycle','The concert is short'],'They overcome delays to reach a concert','Keep the goal and obstacle.'),q('e12',3,'Which detail is usually omitted from a summary?',['colour of a minor object','central problem','main outcome','key claim'],'colour of a minor object','Decoration rarely changes the main idea.')],
['E-WRITE','Writing',3,'Precise, cohesive writing',['E-GRAM','E-SUM'],q('e13',1,'Most precise: “The fox ___ across the field.”',['sprinted','went','did','was'],'sprinted','Choose a verb that shows how.'),q('e14',2,'Contrast: “The route was longer; ___, it was safer.”',['however','therefore','for example','similarly'],'however','The ideas contrast.'),q('e15',3,'Clearer version of “When Ava met Priya, she carried a violin.”',['Priya carried a violin when Ava met her.','When Ava met Priya, she carried it.','Ava met her with one.','They met and she had it.'],'Priya carried a violin when Ava met her.','Naming Priya removes ambiguity.')]
].map(([id,strand,band,title,prerequisites,...items])=>({id,strand,band,title,prerequisites,items}));
export const byItem=id=>objectives.find(o=>o.items.some(i=>i.id===id));
