// Generated by content/build.mjs.
export const mathsPacks = [
  {
    "id": "M-ROUND",
    "strand": "Rounding on a number line",
    "band": 2,
    "title": "Rounding on a number line",
    "prerequisites": [
      "M-NPV"
    ],
    "lesson": {
      "body": "Rounding chooses the nearest multiple, not a separate rounded value for every digit.",
      "example": "3,472 lies between 3,400 and 3,500. The midpoint is 3,450, so it rounds to 3,500 to the nearest hundred.",
      "steps": [
        "Find the multiple just below and just above.",
        "Locate the halfway point.",
        "Choose the nearer end; at exactly halfway choose the higher end."
      ]
    },
    "items": [
      {
        "stem": "Round 133 to the nearest 10.",
        "answer": "130",
        "hint": "Find the two multiples of 10 around 133, then their midpoint.",
        "id": "M-ROUND-1-1",
        "tier": 1,
        "choices": [
          "130",
          "131",
          "129",
          "132"
        ]
      },
      {
        "stem": "Round 145 to the nearest 10.",
        "answer": "150",
        "hint": "Find the two multiples of 10 around 145, then their midpoint.",
        "id": "M-ROUND-1-2",
        "tier": 1,
        "choices": [
          "150",
          "151",
          "149",
          "152"
        ]
      },
      {
        "stem": "Round 157 to the nearest 10.",
        "answer": "160",
        "hint": "Find the two multiples of 10 around 157, then their midpoint.",
        "id": "M-ROUND-1-3",
        "tier": 1,
        "choices": [
          "160",
          "161",
          "159",
          "162"
        ]
      },
      {
        "stem": "Round 1330 to the nearest 100.",
        "answer": "1300",
        "hint": "Find the two multiples of 100 around 1330, then their midpoint.",
        "id": "M-ROUND-2-1",
        "tier": 2,
        "choices": [
          "1300",
          "1301",
          "1299",
          "1302"
        ]
      },
      {
        "stem": "Round 1450 to the nearest 100.",
        "answer": "1500",
        "hint": "Find the two multiples of 100 around 1450, then their midpoint.",
        "id": "M-ROUND-2-2",
        "tier": 2,
        "choices": [
          "1500",
          "1501",
          "1499",
          "1502"
        ]
      },
      {
        "stem": "Round 1570 to the nearest 100.",
        "answer": "1600",
        "hint": "Find the two multiples of 100 around 1570, then their midpoint.",
        "id": "M-ROUND-2-3",
        "tier": 2,
        "choices": [
          "1600",
          "1601",
          "1599",
          "1602"
        ]
      },
      {
        "stem": "Round 13300 to the nearest 1000.",
        "answer": "13000",
        "hint": "Find the two multiples of 1000 around 13300, then their midpoint.",
        "id": "M-ROUND-3-1",
        "tier": 3,
        "choices": [
          "13000",
          "13001",
          "12999",
          "13002"
        ]
      },
      {
        "stem": "Round 14500 to the nearest 1000.",
        "answer": "15000",
        "hint": "Find the two multiples of 1000 around 14500, then their midpoint.",
        "id": "M-ROUND-3-2",
        "tier": 3,
        "choices": [
          "15000",
          "15001",
          "14999",
          "15002"
        ]
      },
      {
        "stem": "Round 15700 to the nearest 1000.",
        "answer": "16000",
        "hint": "Find the two multiples of 1000 around 15700, then their midpoint.",
        "id": "M-ROUND-3-3",
        "tier": 3,
        "choices": [
          "16000",
          "16001",
          "15999",
          "16002"
        ]
      }
    ]
  },
  {
    "id": "M-DECIMAL",
    "strand": "Decimals and place value",
    "band": 2,
    "title": "Decimals and place value",
    "prerequisites": [
      "M-NPV"
    ],
    "lesson": {
      "body": "A decimal point fixes the ones column. Tenths and hundredths are parts of one whole.",
      "example": "0.4 is four tenths, or 40 hundredths. 0.37 is 37 hundredths, so 0.4 is larger.",
      "steps": [
        "Line up the decimal points.",
        "Rename amounts in the same unit.",
        "Compare or combine matching units."
      ]
    },
    "items": [
      {
        "stem": "13 tenths + 3 tenths = how many tenths?",
        "answer": "16",
        "hint": "Both amounts are in tenths, so combine their counts. Keep the unit tenths.",
        "id": "M-DECIMAL-1-1",
        "tier": 1,
        "choices": [
          "16",
          "17",
          "15",
          "18"
        ]
      },
      {
        "stem": "16 tenths + 4 tenths = how many tenths?",
        "answer": "20",
        "hint": "Both amounts are in tenths, so combine their counts. Keep the unit tenths.",
        "id": "M-DECIMAL-1-2",
        "tier": 1,
        "choices": [
          "20",
          "21",
          "19",
          "22"
        ]
      },
      {
        "stem": "19 tenths + 5 tenths = how many tenths?",
        "answer": "24",
        "hint": "Both amounts are in tenths, so combine their counts. Keep the unit tenths.",
        "id": "M-DECIMAL-1-3",
        "tier": 1,
        "choices": [
          "24",
          "25",
          "23",
          "26"
        ]
      },
      {
        "stem": "23 tenths + 3 tenths = how many tenths?",
        "answer": "26",
        "hint": "Both amounts are in tenths, so combine their counts. Keep the unit tenths.",
        "id": "M-DECIMAL-2-1",
        "tier": 2,
        "choices": [
          "26",
          "27",
          "25",
          "28"
        ]
      },
      {
        "stem": "26 tenths + 4 tenths = how many tenths?",
        "answer": "30",
        "hint": "Both amounts are in tenths, so combine their counts. Keep the unit tenths.",
        "id": "M-DECIMAL-2-2",
        "tier": 2,
        "choices": [
          "30",
          "31",
          "29",
          "32"
        ]
      },
      {
        "stem": "29 tenths + 5 tenths = how many tenths?",
        "answer": "34",
        "hint": "Both amounts are in tenths, so combine their counts. Keep the unit tenths.",
        "id": "M-DECIMAL-2-3",
        "tier": 2,
        "choices": [
          "34",
          "35",
          "33",
          "36"
        ]
      },
      {
        "stem": "33 tenths + 3 tenths = how many tenths?",
        "answer": "36",
        "hint": "Both amounts are in tenths, so combine their counts. Keep the unit tenths.",
        "id": "M-DECIMAL-3-1",
        "tier": 3,
        "choices": [
          "36",
          "37",
          "35",
          "38"
        ]
      },
      {
        "stem": "36 tenths + 4 tenths = how many tenths?",
        "answer": "40",
        "hint": "Both amounts are in tenths, so combine their counts. Keep the unit tenths.",
        "id": "M-DECIMAL-3-2",
        "tier": 3,
        "choices": [
          "40",
          "41",
          "39",
          "42"
        ]
      },
      {
        "stem": "39 tenths + 5 tenths = how many tenths?",
        "answer": "44",
        "hint": "Both amounts are in tenths, so combine their counts. Keep the unit tenths.",
        "id": "M-DECIMAL-3-3",
        "tier": 3,
        "choices": [
          "44",
          "45",
          "43",
          "46"
        ]
      }
    ]
  },
  {
    "id": "M-FRACAMT",
    "strand": "Fractions of amounts",
    "band": 2,
    "title": "Fractions of amounts",
    "prerequisites": [
      "M-MULT"
    ],
    "lesson": {
      "body": "The denominator tells how many equal groups. The numerator tells how many groups to take.",
      "example": "Three quarters of 20: make four equal groups of five, then take three groups: 15.",
      "steps": [
        "Divide the amount by the denominator.",
        "Multiply one group by the numerator.",
        "Check the result is sensible."
      ]
    },
    "items": [
      {
        "stem": "What is 1/3 of 15?",
        "answer": "5",
        "hint": "Share 15 into 3 equal groups, then take 1 groups.",
        "id": "M-FRACAMT-1-1",
        "tier": 1,
        "choices": [
          "5",
          "6",
          "4",
          "7"
        ]
      },
      {
        "stem": "What is 1/3 of 18?",
        "answer": "6",
        "hint": "Share 18 into 3 equal groups, then take 1 groups.",
        "id": "M-FRACAMT-1-2",
        "tier": 1,
        "choices": [
          "6",
          "7",
          "5",
          "8"
        ]
      },
      {
        "stem": "What is 1/3 of 21?",
        "answer": "7",
        "hint": "Share 21 into 3 equal groups, then take 1 groups.",
        "id": "M-FRACAMT-1-3",
        "tier": 1,
        "choices": [
          "7",
          "8",
          "6",
          "9"
        ]
      },
      {
        "stem": "What is 2/4 of 20?",
        "answer": "10",
        "hint": "Share 20 into 4 equal groups, then take 2 groups.",
        "id": "M-FRACAMT-2-1",
        "tier": 2,
        "choices": [
          "10",
          "11",
          "9",
          "12"
        ]
      },
      {
        "stem": "What is 2/4 of 24?",
        "answer": "12",
        "hint": "Share 24 into 4 equal groups, then take 2 groups.",
        "id": "M-FRACAMT-2-2",
        "tier": 2,
        "choices": [
          "12",
          "13",
          "11",
          "14"
        ]
      },
      {
        "stem": "What is 2/4 of 28?",
        "answer": "14",
        "hint": "Share 28 into 4 equal groups, then take 2 groups.",
        "id": "M-FRACAMT-2-3",
        "tier": 2,
        "choices": [
          "14",
          "15",
          "13",
          "16"
        ]
      },
      {
        "stem": "What is 3/5 of 25?",
        "answer": "15",
        "hint": "Share 25 into 5 equal groups, then take 3 groups.",
        "id": "M-FRACAMT-3-1",
        "tier": 3,
        "choices": [
          "15",
          "16",
          "14",
          "17"
        ]
      },
      {
        "stem": "What is 3/5 of 30?",
        "answer": "18",
        "hint": "Share 30 into 5 equal groups, then take 3 groups.",
        "id": "M-FRACAMT-3-2",
        "tier": 3,
        "choices": [
          "18",
          "19",
          "17",
          "20"
        ]
      },
      {
        "stem": "What is 3/5 of 35?",
        "answer": "21",
        "hint": "Share 35 into 5 equal groups, then take 3 groups.",
        "id": "M-FRACAMT-3-3",
        "tier": 3,
        "choices": [
          "21",
          "22",
          "20",
          "23"
        ]
      }
    ]
  },
  {
    "id": "M-PERCENT",
    "strand": "Percentages as parts of one hundred",
    "band": 3,
    "title": "Percentages as parts of one hundred",
    "prerequisites": [
      "M-FRACAMT"
    ],
    "lesson": {
      "body": "Percent means out of one hundred. Find a useful small part, then combine parts.",
      "example": "15% of 80: 10% is 8 and 5% is 4. Together they make 12.",
      "steps": [
        "Identify the whole amount.",
        "Find 10%, 1% or another convenient part.",
        "Scale or combine those parts."
      ]
    },
    "items": [
      {
        "stem": "What is 10% of 120?",
        "answer": "12",
        "hint": "Percent means out of 100. Multiply 120 by 10, then divide by 100.",
        "id": "M-PERCENT-1-1",
        "tier": 1,
        "choices": [
          "12",
          "13",
          "11",
          "14"
        ]
      },
      {
        "stem": "What is 10% of 160?",
        "answer": "16",
        "hint": "Percent means out of 100. Multiply 160 by 10, then divide by 100.",
        "id": "M-PERCENT-1-2",
        "tier": 1,
        "choices": [
          "16",
          "17",
          "15",
          "18"
        ]
      },
      {
        "stem": "What is 10% of 200?",
        "answer": "20",
        "hint": "Percent means out of 100. Multiply 200 by 10, then divide by 100.",
        "id": "M-PERCENT-1-3",
        "tier": 1,
        "choices": [
          "20",
          "21",
          "19",
          "22"
        ]
      },
      {
        "stem": "What is 25% of 120?",
        "answer": "30",
        "hint": "Percent means out of 100. Multiply 120 by 25, then divide by 100.",
        "id": "M-PERCENT-2-1",
        "tier": 2,
        "choices": [
          "30",
          "31",
          "29",
          "32"
        ]
      },
      {
        "stem": "What is 25% of 160?",
        "answer": "40",
        "hint": "Percent means out of 100. Multiply 160 by 25, then divide by 100.",
        "id": "M-PERCENT-2-2",
        "tier": 2,
        "choices": [
          "40",
          "41",
          "39",
          "42"
        ]
      },
      {
        "stem": "What is 25% of 200?",
        "answer": "50",
        "hint": "Percent means out of 100. Multiply 200 by 25, then divide by 100.",
        "id": "M-PERCENT-2-3",
        "tier": 2,
        "choices": [
          "50",
          "51",
          "49",
          "52"
        ]
      },
      {
        "stem": "What is 15% of 120?",
        "answer": "18",
        "hint": "Percent means out of 100. Multiply 120 by 15, then divide by 100.",
        "id": "M-PERCENT-3-1",
        "tier": 3,
        "choices": [
          "18",
          "19",
          "17",
          "20"
        ]
      },
      {
        "stem": "What is 15% of 160?",
        "answer": "24",
        "hint": "Percent means out of 100. Multiply 160 by 15, then divide by 100.",
        "id": "M-PERCENT-3-2",
        "tier": 3,
        "choices": [
          "24",
          "25",
          "23",
          "26"
        ]
      },
      {
        "stem": "What is 15% of 200?",
        "answer": "30",
        "hint": "Percent means out of 100. Multiply 200 by 15, then divide by 100.",
        "id": "M-PERCENT-3-3",
        "tier": 3,
        "choices": [
          "30",
          "31",
          "29",
          "32"
        ]
      }
    ]
  },
  {
    "id": "M-TIME",
    "strand": "Elapsed time",
    "band": 2,
    "title": "Elapsed time",
    "prerequisites": [
      "M-CALC"
    ],
    "lesson": {
      "body": "Time durations can be found by counting forward to the next hour, then adding the remaining minutes.",
      "example": "From 09:45 to 10:20: 15 minutes to ten, then 20 more, so 35 minutes.",
      "steps": [
        "Count to the next convenient hour.",
        "Count the rest of the journey.",
        "Add the parts, using 60 minutes per hour."
      ]
    },
    "items": [
      {
        "stem": "How many minutes from 09:10 to 09:46 on the same morning?",
        "answer": "36",
        "hint": "Count forwards. An hour contains 60 minutes, not 100.",
        "id": "M-TIME-1-1",
        "tier": 1,
        "choices": [
          "36",
          "37",
          "35",
          "38"
        ]
      },
      {
        "stem": "How many minutes from 09:20 to 09:57 on the same morning?",
        "answer": "37",
        "hint": "Count forwards. An hour contains 60 minutes, not 100.",
        "id": "M-TIME-1-2",
        "tier": 1,
        "choices": [
          "37",
          "38",
          "36",
          "39"
        ]
      },
      {
        "stem": "How many minutes from 09:30 to 10:08 on the same morning?",
        "answer": "38",
        "hint": "Count forwards. An hour contains 60 minutes, not 100.",
        "id": "M-TIME-1-3",
        "tier": 1,
        "choices": [
          "38",
          "39",
          "37",
          "40"
        ]
      },
      {
        "stem": "How many minutes from 09:10 to 10:06 on the same morning?",
        "answer": "56",
        "hint": "Count forwards. An hour contains 60 minutes, not 100.",
        "id": "M-TIME-2-1",
        "tier": 2,
        "choices": [
          "56",
          "57",
          "55",
          "58"
        ]
      },
      {
        "stem": "How many minutes from 09:20 to 10:17 on the same morning?",
        "answer": "57",
        "hint": "Count forwards. An hour contains 60 minutes, not 100.",
        "id": "M-TIME-2-2",
        "tier": 2,
        "choices": [
          "57",
          "58",
          "56",
          "59"
        ]
      },
      {
        "stem": "How many minutes from 09:30 to 10:28 on the same morning?",
        "answer": "58",
        "hint": "Count forwards. An hour contains 60 minutes, not 100.",
        "id": "M-TIME-2-3",
        "tier": 2,
        "choices": [
          "58",
          "59",
          "57",
          "60"
        ]
      },
      {
        "stem": "How many minutes from 09:10 to 10:26 on the same morning?",
        "answer": "76",
        "hint": "Count forwards. An hour contains 60 minutes, not 100.",
        "id": "M-TIME-3-1",
        "tier": 3,
        "choices": [
          "76",
          "77",
          "75",
          "78"
        ]
      },
      {
        "stem": "How many minutes from 09:20 to 10:37 on the same morning?",
        "answer": "77",
        "hint": "Count forwards. An hour contains 60 minutes, not 100.",
        "id": "M-TIME-3-2",
        "tier": 3,
        "choices": [
          "77",
          "78",
          "76",
          "79"
        ]
      },
      {
        "stem": "How many minutes from 09:30 to 10:48 on the same morning?",
        "answer": "78",
        "hint": "Count forwards. An hour contains 60 minutes, not 100.",
        "id": "M-TIME-3-3",
        "tier": 3,
        "choices": [
          "78",
          "79",
          "77",
          "80"
        ]
      }
    ]
  },
  {
    "id": "M-RATIO",
    "strand": "Ratio and equal shares",
    "band": 3,
    "title": "Ratio and equal shares",
    "prerequisites": [
      "M-MULT"
    ],
    "lesson": {
      "body": "A ratio compares numbers of equal-sized shares. Count all shares before dividing the total.",
      "example": "Red to blue beads are 2:3. With 20 beads, five shares means four beads per share. Red has eight beads.",
      "steps": [
        "Add the numbers in the ratio.",
        "Divide the total by that sum.",
        "Multiply by the shares you need."
      ]
    },
    "items": [
      {
        "stem": "Red to blue beads are 1:2. There are 12 beads altogether. How many are red?",
        "answer": "4",
        "hint": "There are 3 equal shares. Find one share, then take 1 shares.",
        "id": "M-RATIO-1-1",
        "tier": 1,
        "choices": [
          "4",
          "5",
          "3",
          "6"
        ]
      },
      {
        "stem": "Red to blue beads are 1:3. There are 20 beads altogether. How many are red?",
        "answer": "5",
        "hint": "There are 4 equal shares. Find one share, then take 1 shares.",
        "id": "M-RATIO-1-2",
        "tier": 1,
        "choices": [
          "5",
          "6",
          "4",
          "7"
        ]
      },
      {
        "stem": "Red to blue beads are 1:4. There are 30 beads altogether. How many are red?",
        "answer": "6",
        "hint": "There are 5 equal shares. Find one share, then take 1 shares.",
        "id": "M-RATIO-1-3",
        "tier": 1,
        "choices": [
          "6",
          "7",
          "5",
          "8"
        ]
      },
      {
        "stem": "Red to blue beads are 2:2. There are 16 beads altogether. How many are red?",
        "answer": "8",
        "hint": "There are 4 equal shares. Find one share, then take 2 shares.",
        "id": "M-RATIO-2-1",
        "tier": 2,
        "choices": [
          "8",
          "9",
          "7",
          "10"
        ]
      },
      {
        "stem": "Red to blue beads are 2:3. There are 25 beads altogether. How many are red?",
        "answer": "10",
        "hint": "There are 5 equal shares. Find one share, then take 2 shares.",
        "id": "M-RATIO-2-2",
        "tier": 2,
        "choices": [
          "10",
          "11",
          "9",
          "12"
        ]
      },
      {
        "stem": "Red to blue beads are 2:4. There are 36 beads altogether. How many are red?",
        "answer": "12",
        "hint": "There are 6 equal shares. Find one share, then take 2 shares.",
        "id": "M-RATIO-2-3",
        "tier": 2,
        "choices": [
          "12",
          "13",
          "11",
          "14"
        ]
      },
      {
        "stem": "Red to blue beads are 3:2. There are 20 beads altogether. How many are red?",
        "answer": "12",
        "hint": "There are 5 equal shares. Find one share, then take 3 shares.",
        "id": "M-RATIO-3-1",
        "tier": 3,
        "choices": [
          "12",
          "13",
          "11",
          "14"
        ]
      },
      {
        "stem": "Red to blue beads are 3:3. There are 30 beads altogether. How many are red?",
        "answer": "15",
        "hint": "There are 6 equal shares. Find one share, then take 3 shares.",
        "id": "M-RATIO-3-2",
        "tier": 3,
        "choices": [
          "15",
          "16",
          "14",
          "17"
        ]
      },
      {
        "stem": "Red to blue beads are 3:4. There are 42 beads altogether. How many are red?",
        "answer": "18",
        "hint": "There are 7 equal shares. Find one share, then take 3 shares.",
        "id": "M-RATIO-3-3",
        "tier": 3,
        "choices": [
          "18",
          "19",
          "17",
          "20"
        ]
      }
    ]
  },
  {
    "id": "M-ALG",
    "strand": "Missing numbers and inverse operations",
    "band": 3,
    "title": "Missing numbers and inverse operations",
    "prerequisites": [
      "M-CALC"
    ],
    "lesson": {
      "body": "An equation says both sides have equal value. Undo an operation with its inverse.",
      "example": "If x + 7 = 19, subtract seven from both sides to find x = 12.",
      "steps": [
        "Identify what happened to the unknown number.",
        "Undo that operation on both sides.",
        "Put the answer back to check equality."
      ]
    },
    "items": [
      {
        "stem": "Find x: 3 × x = 15.",
        "answer": "5",
        "hint": "Undo multiplication by 3 with division. Then check by multiplying.",
        "id": "M-ALG-1-1",
        "tier": 1,
        "choices": [
          "5",
          "6",
          "4",
          "7"
        ]
      },
      {
        "stem": "Find x: 3 × x = 18.",
        "answer": "6",
        "hint": "Undo multiplication by 3 with division. Then check by multiplying.",
        "id": "M-ALG-1-2",
        "tier": 1,
        "choices": [
          "6",
          "7",
          "5",
          "8"
        ]
      },
      {
        "stem": "Find x: 3 × x = 21.",
        "answer": "7",
        "hint": "Undo multiplication by 3 with division. Then check by multiplying.",
        "id": "M-ALG-1-3",
        "tier": 1,
        "choices": [
          "7",
          "8",
          "6",
          "9"
        ]
      },
      {
        "stem": "Find x: 4 × x = 20.",
        "answer": "5",
        "hint": "Undo multiplication by 4 with division. Then check by multiplying.",
        "id": "M-ALG-2-1",
        "tier": 2,
        "choices": [
          "5",
          "6",
          "4",
          "7"
        ]
      },
      {
        "stem": "Find x: 4 × x = 24.",
        "answer": "6",
        "hint": "Undo multiplication by 4 with division. Then check by multiplying.",
        "id": "M-ALG-2-2",
        "tier": 2,
        "choices": [
          "6",
          "7",
          "5",
          "8"
        ]
      },
      {
        "stem": "Find x: 4 × x = 28.",
        "answer": "7",
        "hint": "Undo multiplication by 4 with division. Then check by multiplying.",
        "id": "M-ALG-2-3",
        "tier": 2,
        "choices": [
          "7",
          "8",
          "6",
          "9"
        ]
      },
      {
        "stem": "Find x: 5 × x = 25.",
        "answer": "5",
        "hint": "Undo multiplication by 5 with division. Then check by multiplying.",
        "id": "M-ALG-3-1",
        "tier": 3,
        "choices": [
          "5",
          "6",
          "4",
          "7"
        ]
      },
      {
        "stem": "Find x: 5 × x = 30.",
        "answer": "6",
        "hint": "Undo multiplication by 5 with division. Then check by multiplying.",
        "id": "M-ALG-3-2",
        "tier": 3,
        "choices": [
          "6",
          "7",
          "5",
          "8"
        ]
      },
      {
        "stem": "Find x: 5 × x = 35.",
        "answer": "7",
        "hint": "Undo multiplication by 5 with division. Then check by multiplying.",
        "id": "M-ALG-3-3",
        "tier": 3,
        "choices": [
          "7",
          "8",
          "6",
          "9"
        ]
      }
    ]
  }
];
