import { escapeHTML as h, summarize } from './attempts.js';
import { objectives } from './content.js';

const seconds=ms=>Number.isFinite(ms)?`${(ms/1000).toFixed(1)} s`:'Not recorded';
function summary(events){const s=summarize(events);return `<p>${s.count} answers · ${s.correct} correct · ${s.supported} supported<br>Typical active response: ${seconds(s.medianMs)} · ${s.rapid} responses under 1.5 s</p>`;}
export function mountReports(root,profile) {
  const events=(profile.events||[]).filter(e=>typeof e.data?.correct==='boolean');
  const topics=[...new Set(events.map(e=>e.data.objectiveId||e.data.topic||'Other'))];
  const name=id=>objectives.find(o=>o.id===id)?.title||id;
  root.innerHTML=`<h3>Learning evidence & replay</h3>${summary(events)}<p class="small">Timing starts when a question appears and pauses when the app is hidden or the parent view is open. Reading, typing, audio and thinking all take time. Under 1.5 seconds is a review flag, not proof of guessing. Older answers have no timing or selected-answer record. Replay is an event reconstruction, not a screen recording.</p><label>Topic<select data-topic><option value="">All topics</option>${topics.map(t=>`<option value="${h(t)}">${h(name(t))}</option>`).join('')}</select></label><label>Session<select data-session><option value="">All sessions</option>${[...new Set(events.map(e=>e.data.sessionId).filter(Boolean))].reverse().map(id=>`<option value="${h(id)}">${h(new Date(events.find(e=>e.data.sessionId===id).ts).toLocaleString())} · ${h(id.slice(0,8))}</option>`).join('')}</select></label><div data-summary></div><div data-questions></div><h4>Replay selected history</h4><div data-replay></div><button data-prev>Previous attempt</button> <button data-next>Next attempt</button><p><button data-export>Download this profile’s history</button></p>`;
  let filtered=events, cursor=0;
  function replay(){const e=filtered[cursor];root.querySelector('[data-replay]').innerHTML=e?`<p>Attempt ${cursor+1} of ${filtered.length} · ${h(new Date(e.ts).toLocaleString())}</p><p><b>${h(e.data.stem||e.data.itemId||e.data.wordId)}</b></p>${e.data.choices?.length?`<ol>${e.data.choices.map(c=>`<li>${h(c)}${c===e.data.response?' ← selected':''}</li>`).join('')}</ol>`:''}<p>Response: ${h(e.data.response??'Not recorded')}<br>Expected: ${h(e.data.expected??'Not recorded')}<br>${e.data.correct?'Correct':'Needs another look'}${e.data.supported?' · after support':''} · ${seconds(e.data.responseMs)} active · ${seconds(e.data.elapsedMs)} elapsed</p><p>${h(e.data.feedback||'Feedback not recorded')}</p>`:'No answers in this selection.';root.querySelector('[data-prev]').disabled=cursor<=0;root.querySelector('[data-next]').disabled=cursor>=filtered.length-1;}
  function render(){const topic=root.querySelector('[data-topic]').value,session=root.querySelector('[data-session]').value;filtered=events.filter(e=>(!topic||(e.data.objectiveId||e.data.topic||'Other')===topic)&&(!session||e.data.sessionId===session));cursor=0;root.querySelector('[data-summary]').innerHTML=summary(filtered);
    const keys=[...new Set(filtered.map(e=>e.data.itemId||e.data.wordId))];
    root.querySelector('[data-questions]').innerHTML=keys.map(key=>{const rows=filtered.filter(e=>(e.data.itemId||e.data.wordId)===key);return `<details><summary>${h(rows[0].data.stem||key)}</summary>${summary(rows)}${rows.map(e=>`<p class="small">${h(new Date(e.ts).toLocaleString())} · ${e.data.correct?'Correct':'Needs another look'} · ${seconds(e.data.responseMs)} · ${h(e.data.response??'response not recorded')}</p>`).join('')}</details>`;}).join('');replay();}
  root.querySelector('[data-topic]').onchange=render;root.querySelector('[data-session]').onchange=render;
  root.querySelector('[data-prev]').onclick=()=>{cursor--;replay();};root.querySelector('[data-next]').onclick=()=>{cursor++;replay();};
  root.querySelector('[data-export]').onclick=()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify({version:1,events},null,2)],{type:'application/json'}));a.href=url;a.download='learning-history.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};render();
}
