// Generated by content/build.mjs. Edit content/words-source.tsv.
export const words = [
  {
    "id": "word-said",
    "year": 1,
    "word": "said",
    "meaning": "spoke some words",
    "sentence": "She said that the kite was blue."
  },
  {
    "id": "word-come",
    "year": 1,
    "word": "come",
    "meaning": "move towards this place",
    "sentence": "Please come to the table."
  },
  {
    "id": "word-some",
    "year": 1,
    "word": "some",
    "meaning": "an amount that is not exact",
    "sentence": "There are some apples in the bowl."
  },
  {
    "id": "word-one",
    "year": 1,
    "word": "one",
    "meaning": "a single thing",
    "sentence": "There is one boat by the bank."
  },
  {
    "id": "word-once",
    "year": 1,
    "word": "once",
    "meaning": "on one occasion",
    "sentence": "I have visited that park once."
  },
  {
    "id": "word-friend",
    "year": 1,
    "word": "friend",
    "meaning": "someone you like and know well",
    "sentence": "My friend helped me build a den."
  },
  {
    "id": "word-school",
    "year": 1,
    "word": "school",
    "meaning": "a place where people learn together",
    "sentence": "The school has a library."
  },
  {
    "id": "word-house",
    "year": 1,
    "word": "house",
    "meaning": "a building where people live",
    "sentence": "The house has a green door."
  },
  {
    "id": "word-where",
    "year": 1,
    "word": "where",
    "meaning": "in or at what place",
    "sentence": "Where did you put the map?"
  },
  {
    "id": "word-there",
    "year": 1,
    "word": "there",
    "meaning": "in or at that place",
    "sentence": "Put the basket over there."
  },
  {
    "id": "word-brave",
    "year": 1,
    "word": "brave",
    "meaning": "willing to face something frightening",
    "sentence": "The brave sailor asked for help in the storm."
  },
  {
    "id": "word-tiny",
    "year": 1,
    "word": "tiny",
    "meaning": "very small",
    "sentence": "A tiny seed lay on my hand."
  },
  {
    "id": "word-because",
    "year": 2,
    "word": "because",
    "meaning": "for the reason that",
    "sentence": "We stayed inside because it rained."
  },
  {
    "id": "word-beautiful",
    "year": 2,
    "word": "beautiful",
    "meaning": "very pleasing to look at or experience",
    "sentence": "The beautiful garden was full of flowers."
  },
  {
    "id": "word-people",
    "year": 2,
    "word": "people",
    "meaning": "human beings",
    "sentence": "Several people waited for the bus."
  },
  {
    "id": "word-again",
    "year": 2,
    "word": "again",
    "meaning": "one more time",
    "sentence": "Read the sentence again."
  },
  {
    "id": "word-every",
    "year": 2,
    "word": "every",
    "meaning": "each one of a group",
    "sentence": "Every chair had a cushion."
  },
  {
    "id": "word-could",
    "year": 2,
    "word": "could",
    "meaning": "was able to or might be able to",
    "sentence": "I could see the hill from the window."
  },
  {
    "id": "word-would",
    "year": 2,
    "word": "would",
    "meaning": "used to describe an imagined action",
    "sentence": "I would sail if the wind returned."
  },
  {
    "id": "word-should",
    "year": 2,
    "word": "should",
    "meaning": "used to say what is advisable",
    "sentence": "We should check the map before leaving."
  },
  {
    "id": "word-climb",
    "year": 2,
    "word": "climb",
    "meaning": "move upwards using your hands or feet",
    "sentence": "We climb the steps to the tower."
  },
  {
    "id": "word-quiet",
    "year": 2,
    "word": "quiet",
    "meaning": "making little noise",
    "sentence": "The quiet room helped us hear the clock."
  },
  {
    "id": "word-gentle",
    "year": 2,
    "word": "gentle",
    "meaning": "careful and not rough",
    "sentence": "Use a gentle touch with the young plant."
  },
  {
    "id": "word-enormous",
    "year": 2,
    "word": "enormous",
    "meaning": "extremely large",
    "sentence": "The enormous ship filled the harbour."
  },
  {
    "id": "word-accident",
    "year": 3,
    "word": "accident",
    "meaning": "an unexpected event that can cause damage",
    "sentence": "The broken cup was an accident."
  },
  {
    "id": "word-address",
    "year": 3,
    "word": "address",
    "meaning": "details of where someone lives or a place is",
    "sentence": "Write the address on the envelope."
  },
  {
    "id": "word-answer",
    "year": 3,
    "word": "answer",
    "meaning": "a reply to a question",
    "sentence": "Explain how you found your answer."
  },
  {
    "id": "word-appear",
    "year": 3,
    "word": "appear",
    "meaning": "come into sight",
    "sentence": "Stars appear as the sky grows dark."
  },
  {
    "id": "word-arrive",
    "year": 3,
    "word": "arrive",
    "meaning": "reach a place",
    "sentence": "We will arrive before lunch."
  },
  {
    "id": "word-believe",
    "year": 3,
    "word": "believe",
    "meaning": "think that something is true",
    "sentence": "I believe the bridge is open."
  },
  {
    "id": "word-bicycle",
    "year": 3,
    "word": "bicycle",
    "meaning": "a vehicle with two wheels driven by pedals",
    "sentence": "I parked my bicycle beside the gate."
  },
  {
    "id": "word-calendar",
    "year": 3,
    "word": "calendar",
    "meaning": "a chart showing days and months",
    "sentence": "Mark the trip on the calendar."
  },
  {
    "id": "word-certain",
    "year": 3,
    "word": "certain",
    "meaning": "sure about something",
    "sentence": "I am certain that two plus two is four."
  },
  {
    "id": "word-curious",
    "year": 3,
    "word": "curious",
    "meaning": "wanting to know or learn more",
    "sentence": "The curious child examined the shell."
  },
  {
    "id": "word-fragile",
    "year": 3,
    "word": "fragile",
    "meaning": "easily broken or damaged",
    "sentence": "Carry the fragile glass carefully."
  },
  {
    "id": "word-reluctant",
    "year": 3,
    "word": "reluctant",
    "meaning": "not willing or eager to do something",
    "sentence": "She was reluctant to leave the warm room."
  },
  {
    "id": "word-different",
    "year": 4,
    "word": "different",
    "meaning": "not the same",
    "sentence": "The two leaves have different shapes."
  },
  {
    "id": "word-difficult",
    "year": 4,
    "word": "difficult",
    "meaning": "needing effort or skill to do",
    "sentence": "The difficult puzzle took several attempts."
  },
  {
    "id": "word-disappear",
    "year": 4,
    "word": "disappear",
    "meaning": "stop being visible",
    "sentence": "We watched the boat disappear into the mist."
  },
  {
    "id": "word-experiment",
    "year": 4,
    "word": "experiment",
    "meaning": "a test used to find something out",
    "sentence": "Our experiment compared two types of soil."
  },
  {
    "id": "word-favourite",
    "year": 4,
    "word": "favourite",
    "meaning": "liked more than the others",
    "sentence": "This is my favourite story."
  },
  {
    "id": "word-knowledge",
    "year": 4,
    "word": "knowledge",
    "meaning": "facts and understanding gained by learning",
    "sentence": "Reading expanded his knowledge of birds."
  },
  {
    "id": "word-library",
    "year": 4,
    "word": "library",
    "meaning": "a place where books are kept for people to use",
    "sentence": "I borrowed a book from the library."
  },
  {
    "id": "word-ordinary",
    "year": 4,
    "word": "ordinary",
    "meaning": "usual rather than special",
    "sentence": "It looked like an ordinary stone."
  },
  {
    "id": "word-peculiar",
    "year": 4,
    "word": "peculiar",
    "meaning": "strange or unusual",
    "sentence": "A peculiar sound came from the old clock."
  },
  {
    "id": "word-separate",
    "year": 4,
    "word": "separate",
    "meaning": "apart rather than joined together",
    "sentence": "Keep the wet and dry towels separate."
  },
  {
    "id": "word-cautious",
    "year": 4,
    "word": "cautious",
    "meaning": "careful to avoid danger or mistakes",
    "sentence": "The cautious walker tested the slippery step."
  },
  {
    "id": "word-generous",
    "year": 4,
    "word": "generous",
    "meaning": "willing to give or share",
    "sentence": "The generous gardener shared her seeds."
  },
  {
    "id": "word-accommodate",
    "year": 5,
    "word": "accommodate",
    "meaning": "provide enough space or what is needed",
    "sentence": "The hall can accommodate fifty chairs."
  },
  {
    "id": "word-accompany",
    "year": 5,
    "word": "accompany",
    "meaning": "go somewhere with someone",
    "sentence": "An adult will accompany the group."
  },
  {
    "id": "word-achieve",
    "year": 5,
    "word": "achieve",
    "meaning": "succeed in doing something you worked towards",
    "sentence": "Small steps can help you achieve your aim."
  },
  {
    "id": "word-awkward",
    "year": 5,
    "word": "awkward",
    "meaning": "difficult to handle or move comfortably",
    "sentence": "The long box was awkward to carry."
  },
  {
    "id": "word-bargain",
    "year": 5,
    "word": "bargain",
    "meaning": "something bought for a good price",
    "sentence": "The sturdy second-hand desk was a bargain."
  },
  {
    "id": "word-category",
    "year": 5,
    "word": "category",
    "meaning": "a group of things with shared features",
    "sentence": "Put each animal in the correct category."
  },
  {
    "id": "word-conscience",
    "year": 5,
    "word": "conscience",
    "meaning": "your sense of whether your actions are right or wrong",
    "sentence": "Her conscience prompted her to return the lost coin."
  },
  {
    "id": "word-conscious",
    "year": 5,
    "word": "conscious",
    "meaning": "awake and aware of what is happening",
    "sentence": "He remained conscious after the fall."
  },
  {
    "id": "word-definite",
    "year": 5,
    "word": "definite",
    "meaning": "clear and certain",
    "sentence": "We need a definite time to meet."
  },
  {
    "id": "word-desperate",
    "year": 5,
    "word": "desperate",
    "meaning": "feeling an urgent and serious need",
    "sentence": "The thirsty walkers were desperate for water."
  },
  {
    "id": "word-diligent",
    "year": 5,
    "word": "diligent",
    "meaning": "working with steady care and effort",
    "sentence": "The diligent researcher checked each measurement."
  },
  {
    "id": "word-ambiguous",
    "year": 5,
    "word": "ambiguous",
    "meaning": "having more than one possible meaning",
    "sentence": "The ambiguous message left us unsure which gate to use."
  },
  {
    "id": "word-embarrass",
    "year": 6,
    "word": "embarrass",
    "meaning": "make someone feel awkward or self-conscious",
    "sentence": "Please do not embarrass anyone about a mistake."
  },
  {
    "id": "word-environment",
    "year": 6,
    "word": "environment",
    "meaning": "the surroundings in which living things exist",
    "sentence": "A clean pond is a healthier environment for frogs."
  },
  {
    "id": "word-exaggerate",
    "year": 6,
    "word": "exaggerate",
    "meaning": "describe something as bigger or more extreme than it is",
    "sentence": "Do not exaggerate the size of the fish."
  },
  {
    "id": "word-foreign",
    "year": 6,
    "word": "foreign",
    "meaning": "from another country",
    "sentence": "The museum displayed foreign coins."
  },
  {
    "id": "word-guarantee",
    "year": 6,
    "word": "guarantee",
    "meaning": "a firm promise that something will happen or work",
    "sentence": "The shop gave a guarantee with the clock."
  },
  {
    "id": "word-necessary",
    "year": 6,
    "word": "necessary",
    "meaning": "needed for a particular purpose",
    "sentence": "Water is necessary for the plant to grow."
  },
  {
    "id": "word-opportunity",
    "year": 6,
    "word": "opportunity",
    "meaning": "a chance to do something",
    "sentence": "The visit was an opportunity to ask questions."
  },
  {
    "id": "word-privilege",
    "year": 6,
    "word": "privilege",
    "meaning": "a special right or advantage",
    "sentence": "Access to the private garden was a privilege."
  },
  {
    "id": "word-rhythm",
    "year": 6,
    "word": "rhythm",
    "meaning": "a repeated pattern of beats or movement",
    "sentence": "We clapped the rhythm of the song."
  },
  {
    "id": "word-sufficient",
    "year": 6,
    "word": "sufficient",
    "meaning": "enough for what is needed",
    "sentence": "We had sufficient rope to reach the post."
  },
  {
    "id": "word-meticulous",
    "year": 6,
    "word": "meticulous",
    "meaning": "extremely careful about small details",
    "sentence": "Her meticulous notes recorded every change."
  },
  {
    "id": "word-resilient",
    "year": 6,
    "word": "resilient",
    "meaning": "able to recover after difficulty or damage",
    "sentence": "The resilient plant grew new leaves after the frost."
  },
  {
    "id": "word-benevolent",
    "year": 7,
    "word": "benevolent",
    "meaning": "kind and wishing to help others",
    "sentence": "The benevolent donor paid for new library books."
  },
  {
    "id": "word-coherent",
    "year": 7,
    "word": "coherent",
    "meaning": "clear and logically connected",
    "sentence": "The explanation was coherent and easy to follow."
  },
  {
    "id": "word-concise",
    "year": 7,
    "word": "concise",
    "meaning": "expressed clearly in few words",
    "sentence": "Give a concise summary of the journey."
  },
  {
    "id": "word-conspicuous",
    "year": 7,
    "word": "conspicuous",
    "meaning": "easy to notice",
    "sentence": "The bright orange flag was conspicuous against the snow."
  },
  {
    "id": "word-detrimental",
    "year": 7,
    "word": "detrimental",
    "meaning": "causing harm or damage",
    "sentence": "Too little water is detrimental to these plants."
  },
  {
    "id": "word-eloquent",
    "year": 7,
    "word": "eloquent",
    "meaning": "able to express ideas clearly and effectively",
    "sentence": "Her eloquent speech explained why the park mattered."
  },
  {
    "id": "word-ephemeral",
    "year": 7,
    "word": "ephemeral",
    "meaning": "lasting for only a short time",
    "sentence": "The ephemeral rainbow vanished within minutes."
  },
  {
    "id": "word-frugal",
    "year": 7,
    "word": "frugal",
    "meaning": "careful to avoid wasting money or resources",
    "sentence": "The frugal cook used the remaining vegetables in soup."
  },
  {
    "id": "word-impartial",
    "year": 7,
    "word": "impartial",
    "meaning": "fair and not favouring either side",
    "sentence": "An impartial judge listens to both arguments."
  },
  {
    "id": "word-inevitable",
    "year": 7,
    "word": "inevitable",
    "meaning": "certain to happen and unable to be avoided",
    "sentence": "With no support left, the tower's collapse was inevitable."
  },
  {
    "id": "word-plausible",
    "year": 7,
    "word": "plausible",
    "meaning": "seeming reasonable or possible",
    "sentence": "A loose wire was a plausible explanation for the fault."
  },
  {
    "id": "word-scrutinise",
    "year": 7,
    "word": "scrutinise",
    "meaning": "examine very carefully",
    "sentence": "Scrutinise the map before choosing a route."
  },
  {
    "id": "word-tenacious",
    "year": 7,
    "word": "tenacious",
    "meaning": "continuing firmly despite difficulty",
    "sentence": "The tenacious vine held tightly to the wall."
  },
  {
    "id": "word-transient",
    "year": 7,
    "word": "transient",
    "meaning": "remaining for only a short time",
    "sentence": "The shower was transient and sunshine soon returned."
  },
  {
    "id": "word-vigilant",
    "year": 7,
    "word": "vigilant",
    "meaning": "watchful for possible danger or problems",
    "sentence": "The vigilant lookout spotted the approaching rocks."
  }
];
